# Home Work 01 
1. Numpy 
1. Pytorch (tensor (basic operations))

# DEADLINE

### IS-142 - 08.10.24 
### IS-141 - 15.10.24

## BLOKE №1 (numpy) 

1. Импортировать NumPy под именем np

In [6]:
import numpy as np

2. Создать вектор (одномерный массив) размера 20, заполненный нулями

In [2]:
arr = np.array([0] * 20)
arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

3. Создать вектор размера 20, заполненный числом 1.75

In [3]:
arr = np.array([1.75] * 20)
arr

array([1.75, 1.75, 1.75, 1.75, 1.75, 1.75, 1.75, 1.75, 1.75, 1.75, 1.75,
       1.75, 1.75, 1.75, 1.75, 1.75, 1.75, 1.75, 1.75, 1.75])

4. Создать вектор со значениями от 4 до 31

In [4]:
arr = np.array([i for i in range(4, 32)])
arr

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
       21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

5. Развернуть вектор (первый становится последним)

In [5]:
arr = np.array([i for i in range(4, 32)])
arr = arr[::-1]
arr

array([31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4])

6. Создать матрицу (двумерный массив) 3x3 со значениями от 1 до 9

In [6]:
mtr = np.arange(1,10).reshape(3, 3)
mtr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

7. Создать 3x3 единичную матрицу

In [7]:
mtr = np.eye(3)
mtr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

8. Создать 4x4 пустую матрицу

In [8]:
mtr = np.empty((3, 3))
mtr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

9. Создать единичную матрицу 4x4 со сдвигом на единицу вниз относительно главной диагонали

In [9]:
mtr = np.eye(3, 3, -2)
mtr

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 0., 0.]])

10. Создать тензор 3x3x3 со случайными значениями

In [10]:
import numpy.random as rnd
t = np.array(np.array([[[rnd.random()] * 3] * 3 for _ in range(3)]))
t

array([[[0.91103899, 0.91103899, 0.91103899],
        [0.91103899, 0.91103899, 0.91103899],
        [0.91103899, 0.91103899, 0.91103899]],

       [[0.53241296, 0.53241296, 0.53241296],
        [0.53241296, 0.53241296, 0.53241296],
        [0.53241296, 0.53241296, 0.53241296]],

       [[0.47138097, 0.47138097, 0.47138097],
        [0.47138097, 0.47138097, 0.47138097],
        [0.47138097, 0.47138097, 0.47138097]]])

11. Создать массив 5x5 со случайными значениями, найти минимум и максимум

In [11]:
arr = np.array([[rnd.random() for _ in range(5)] for _ in range(5)])
arr.max(), arr.min()

(np.float64(0.9921107010643505), np.float64(0.0647594942903944))

12. Создать случайный вектор размера 50 и найти среднее значение всех элементов

In [12]:
arr = np.array([rnd.random() for _ in range(50)])
avg = sum(arr) / len(arr)
avg

np.float64(0.47160922954020534)

13. Создать матрицу с 0 внутри, и 1 на границах

In [13]:
m, n = 5, 5
mat = np.matrix([[int(i == 0 or i == n - 1 or j == 0 or j == m - 1) \
                for i in range(n)] \
                for j in range(m)])
mat

matrix([[1, 1, 1, 1, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 1, 1, 1, 1]])

14. Создать 5x5 матрицу с 1,2,3,4 под диагональю

In [14]:
m, n = 5, 5
mat = np.matrix([[ i + 1 if i == j - 1 else 0 \
                for i in range(n)] \
                for j in range(m)])
mat

matrix([[0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [0, 2, 0, 0, 0],
        [0, 0, 3, 0, 0],
        [0, 0, 0, 4, 0]])

15. Перемножить матрицы 5x3 и 3x2

In [15]:
m, n, k = 5, 3, 2
mat1 = np.matrix([[ j * m + i \
                for i in range(n)] \
                for j in range(m)])

mat2 = np.matrix([[ j * k + i \
                for i in range(k)] \
                for j in range(n)])

np.dot(mat1, mat2)

matrix([[ 10,  13],
        [ 40,  58],
        [ 70, 103],
        [100, 148],
        [130, 193]])

16. Создать вектор состоящий из 15 элементов, поменять знак у элементов, значения которых между 6 и 12 

In [16]:
arr = np.array([i if i < 6 or i > 12 else -i for i in range(15)])
arr

array([  0,   1,   2,   3,   4,   5,  -6,  -7,  -8,  -9, -10, -11, -12,
        13,  14])

17. Создать 2 матрицы A(3x3) и B(3x3), получить матрицу С путем поэлеметного умножения.

In [17]:
A = np.array([[j * 3 + i for i in range(3)] for j in range(3)])
B = np.array([[j * 3 + i for i in range(3)] for j in range(3)])
C = A * B
C

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

18. Найти максимальные и минимальные значения матрицы С по строкам и столбцам

19. Создать вектор со значениями от 0 до 1 c 10 наблюдениями

In [18]:
arr = np.arange(0, 1, 0.1)
arr

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

20. Отсортировать вектор

In [19]:
arr = np.array(np.random.randint(1, 10, size=10))
print(arr)
print(np.sort(arr))

[1 7 4 4 9 1 7 4 9 4]
[1 1 4 4 4 4 7 7 9 9]


21. Проверить, одинаковы ли 2 numpy массива

In [20]:
arr1 = np.array(np.random.randint(1, 10, size=10))
arr2 = np.array(np.random.randint(1, 10, size=10))

print(arr1)
print(arr2)
print(all(arr1 == arr2))

[2 3 4 7 9 6 1 5 8 7]
[6 6 3 9 4 1 5 7 8 1]
False


22. Сделать массив неизменяемым

In [21]:
arr = np.array(np.random.randint(1, 10, size=10))

arr.flags.writeable = False

try:
    arr[0] = 0
except ValueError as e:
    print(e)

assignment destination is read-only


23. Создать случайный вектор из 20 элементов, найти квантиль от 10% и от 80%

In [22]:
arr = np.random.random(20)
print(arr)
print(np.quantile(arr, 0.1), np.quantile(arr, 0.8))

[0.9050465  0.58806099 0.53123374 0.82784654 0.59879926 0.44556623
 0.92277398 0.74284369 0.58246485 0.86955505 0.36795669 0.17833863
 0.23755977 0.41928267 0.15728534 0.33474481 0.09946741 0.78745615
 0.04340215 0.92219938]
0.1515035454622641 0.8361882449667071


24. Создать массив любой размерности состоящий из int и string

In [23]:
arr = np.array([1, "asd"], dtype=object)
arr

array([1, 'asd'], dtype=object)

25. Найти минимальное и максимальное значение, принимаемое каждым числовым типом numpy

In [9]:
print(np.iinfo(np.int8).min, np.iinfo(np.int8).max)
print(np.iinfo(np.int16).min, np.iinfo(np.int16).max)
print(np.iinfo(np.int32).min, np.iinfo(np.int32).max)
print(np.iinfo(np.int64).min, np.iinfo(np.int64).max)
print(np.finfo(np.float32).min, np.finfo(np.float32).max)
print(np.finfo(np.float64).min, np.finfo(np.float64).max)

-128 127
-32768 32767
-2147483648 2147483647
-9223372036854775808 9223372036854775807
-3.4028235e+38 3.4028235e+38
-1.7976931348623157e+308 1.7976931348623157e+308


26. Преобразовать массив из float в int

In [11]:
arr = np.array([3.14, 6.28])
arr.astype(int)

array([3, 6])

27. Отнять среднее из каждой строки в матрице

In [20]:
matrix = np.random.random((3, 3))
matrix - np.mean(matrix)

array([[ 0.21089025, -0.17472387, -0.37522255],
       [-0.19926603, -0.09396435,  0.32574459],
       [ 0.3781951 ,  0.24784132, -0.31949445]])

28. 

Дана данные из файла.

1,2,3,4,5

6,,,7,8

,,9,10,11

Необходимо прочитать его


In [22]:
data = np.genfromtxt('data.csv', delimiter=',')
print(data)

[[ 1.  2.  3.  4.  5.]
 [ 6. nan nan  7.  8.]
 [nan nan  9. 10. 11.]]


29. Посчитайте сумму квадратов натуральных чисел от 1 до 10000.

In [28]:
n = np.arange(1, 10001)
sum(n**2)

np.int64(333383335000)

## BLOKE №2 (tensors) 

1. Импортируйте pytorch

In [3]:
import torch

2. Создать вектор состящий из 10 элементов

In [4]:
torch.arange(10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

3. Создать тензор из python list

In [31]:
torch.tensor([1, 2, 3, 4])

tensor([1, 2, 3, 4])

4. Создать тензор из np.array

In [32]:
arr = np.arange(27).reshape(3, 3, 3)
t = torch.tensor(arr)
t

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]])

5. Создать тензор с нормальным распределением

In [33]:
t = torch.normal(10, 5, (3, 3))
t

tensor([[ 9.0896,  4.6389,  2.8441],
        [ 6.4328,  4.0427,  6.1318],
        [ 1.1008, 18.2919, 14.9683]])

6. Создать тензор размером 3х3х3

In [34]:
t = torch.arange(27).reshape(3, 3, 3)
t

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]])

7. Создать единичную матрицу размером 4х5

In [35]:
t = torch.eye(4, 5)
t

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.]])

8. Создать вектор размера 25, заполнить елементами со значениме pi

In [36]:
vec = torch.full([25], torch.pi)
vec

tensor([3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416,
        3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416,
        3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416])

9. Умножить матрицу размера 9, заполненная от 0 до 8, поэлементно на любое число

In [37]:
mtr = torch.arange(9).reshape(3, 3)
mtr = mtr * 3
mtr

tensor([[ 0,  3,  6],
        [ 9, 12, 15],
        [18, 21, 24]])

10. Создать произвольный тензор с типом данных int8

In [38]:
t = torch.full([3, 5, 2, 2], 1 ,dtype=torch.int8)
t

tensor([[[[1, 1],
          [1, 1]],

         [[1, 1],
          [1, 1]],

         [[1, 1],
          [1, 1]],

         [[1, 1],
          [1, 1]],

         [[1, 1],
          [1, 1]]],


        [[[1, 1],
          [1, 1]],

         [[1, 1],
          [1, 1]],

         [[1, 1],
          [1, 1]],

         [[1, 1],
          [1, 1]],

         [[1, 1],
          [1, 1]]],


        [[[1, 1],
          [1, 1]],

         [[1, 1],
          [1, 1]],

         [[1, 1],
          [1, 1]],

         [[1, 1],
          [1, 1]],

         [[1, 1],
          [1, 1]]]], dtype=torch.int8)

11. Изменить тип данных из пункта 10 на int64

In [39]:
t = torch.full([3, 5, 2, 2], 1 ,dtype=torch.int64)
t

tensor([[[[1, 1],
          [1, 1]],

         [[1, 1],
          [1, 1]],

         [[1, 1],
          [1, 1]],

         [[1, 1],
          [1, 1]],

         [[1, 1],
          [1, 1]]],


        [[[1, 1],
          [1, 1]],

         [[1, 1],
          [1, 1]],

         [[1, 1],
          [1, 1]],

         [[1, 1],
          [1, 1]],

         [[1, 1],
          [1, 1]]],


        [[[1, 1],
          [1, 1]],

         [[1, 1],
          [1, 1]],

         [[1, 1],
          [1, 1]],

         [[1, 1],
          [1, 1]],

         [[1, 1],
          [1, 1]]]])

12. Создать случайный тензор размера 4x5 и найти среднее по 2му столбцу.

In [40]:
t = torch.rand(4, 5)
avg = sum(t[1]) / len(t[1])
print(t)
avg

tensor([[0.1566, 0.8185, 0.2237, 0.1183, 0.3617],
        [0.0800, 0.3078, 0.0235, 0.5717, 0.2572],
        [0.7458, 0.4128, 0.3709, 0.2362, 0.9456],
        [0.3269, 0.2006, 0.1325, 0.8815, 0.3393]])


tensor(0.2480)

13. Создать пустой тензор произвольных размеров

In [41]:
t = torch.empty([3,3,3,3])
t

tensor([[[[2.4677e-40, 0.0000e+00, 0.0000e+00],
          [0.0000e+00,        nan, 0.0000e+00],
          [4.2324e+21, 1.7033e+19, 1.0899e+27]],

         [[4.3210e+27, 2.7554e+23, 1.6458e+19],
          [1.9284e+31, 2.7010e+26, 1.9618e+20],
          [3.4590e-12, 2.0572e+26, 1.1446e+24]],

         [[9.1042e-12, 1.1028e+21, 7.2065e+31],
          [2.4471e+32, 2.7374e+20, 2.6219e+20],
          [2.1127e-19, 1.8990e+28, 2.9602e+29]]],


        [[[7.1447e+31, 2.2266e-15, 1.7753e+28],
          [3.0110e+29, 2.6908e+20, 4.4894e+21],
          [1.6928e+22, 1.7667e+22, 6.8888e+22]],

         [[6.6813e+22, 1.1096e+27, 2.4622e-15],
          [7.3988e+31, 4.4849e+21, 2.7370e+20],
          [6.4640e-04, 1.8461e+20, 9.0941e-04]],

         [[7.0968e+22, 1.0900e+27, 2.6223e+20],
          [1.6458e+19, 1.7260e+25, 1.6928e+22],
          [1.8174e+31, 1.7034e+19, 2.8895e+12]]],


        [[[7.5338e+28, 5.5095e-14, 1.6109e-19],
          [1.8888e+31, 1.1727e-19, 7.2128e+22],
          [1.4755e+31, 1

14. Скалярно умножить 2 вектора

In [42]:
v1 = torch.tensor([1, 2, 3])
v2 = torch.tensor([4, 5, 6])
torch.dot(v1, v2)

tensor(32)

15. Умножить матрицу на вектор

In [43]:
v = torch.tensor([1, 2, 3])
mtr = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

r = torch.matmul(mtr, v)
r

tensor([14, 32, 50])

16. Перемножить 2D матрицы 

In [44]:
mtr1 = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
mtr2 = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

r = torch.matmul(mtr1, mtr2)
r

tensor([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

17. Перемножить 3D тензоры

In [45]:
t1 = torch.arange(27).reshape(3, 3, 3)
t2 = torch.arange(27).reshape(3, 3, 3)

torch.matmul(t1, t2)


tensor([[[  15,   18,   21],
         [  42,   54,   66],
         [  69,   90,  111]],

        [[ 366,  396,  426],
         [ 474,  513,  552],
         [ 582,  630,  678]],

        [[1203, 1260, 1317],
         [1392, 1458, 1524],
         [1581, 1656, 1731]]])

18. Создать вектор с нормальным распределением и вывести элементы больше 0.5

In [46]:
vec = torch.normal(1, 0.5, [10])

f = list(filter(lambda x: x > 0.5, vec))
print(f)

[tensor(0.7987), tensor(0.9188), tensor(0.5581), tensor(1.1812), tensor(0.8352), tensor(1.3472), tensor(1.1370)]


19. Создать матрицу 3х3 заполненную единицами и заменить 1й столбец на 4

In [47]:
m = torch.full([3, 3], 1)
print(m)
m[:, 0] = torch.full([3], 4)
print(m)


tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])
tensor([[4, 1, 1],
        [4, 1, 1],
        [4, 1, 1]])


20. Создать матрицу и вывести сумму по каждой строке

In [48]:
m = torch.full([3, 3], 1)
print(m)

for i in m:
    print(sum(i))

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])
tensor(3)
tensor(3)
tensor(3)


20. Создать матрицу и вывести среднее по каждому столбцу

In [49]:
m = torch.rand([3, 3])
print(m)

for i in m.T:
    print(sum(i)/len(i))

tensor([[0.8360, 0.9626, 0.1792],
        [0.1984, 0.7758, 0.5612],
        [0.3179, 0.8818, 0.6596]])
tensor(0.4507)
tensor(0.8734)
tensor(0.4667)


21. Создать 2 вектора и сконкатенировать по 1 оси

In [6]:
v1 = torch.tensor([1, 2, 3])
v2 = torch.tensor([4, 5, 6])

torch.cat((v1, v2), dim=0)

tensor([1, 2, 3, 4, 5, 6])

22. Перемножим две большие единичные матрицы. 
Сначал на центральном процессоре, затем попробуйте на GPU

In [31]:
import torch
import time

m1 = torch.arange(100000000).reshape(10000, 10000).to(torch.float32)
m2 = torch.arange(100000000).reshape(10000, 10000).to(torch.float32)

start_time = time.time()

cpu = torch.matmul(m1, m2)

end_time = time.time()
execution_time = end_time - start_time
print(f"Время выполнения cpu: {execution_time:.6f} секунд")

if torch.cuda.is_available():
    m1_gpu = m1.to('cuda')
    m2_gpu = m2.to('cuda')

    start_time = time.time()

    gpu = torch.matmul(m1_gpu, m2_gpu)

    end_time = time.time()
    execution_time = end_time - start_time
    print(f"Время выполнения gpu: {execution_time:.6f} секунд") 
else:
    print("GPU недоступен")

Время выполнения cpu: 4.795533 секунд
GPU недоступен
