# Home Work 01 
1. Numpy 
1. Pytorch (tensor (basic operations))

# DEADLINE

### IS-142 - 08.10.24 
### IS-141 - 15.10.24

## BLOKE №1 (numpy) 

1. Импортировать NumPy под именем np

In [218]:
import numpy as np

2. Создать вектор (одномерный массив) размера 20, заполненный нулями

In [219]:
arr = np.array([0] * 20)
arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

3. Создать вектор размера 20, заполненный числом 1.75

In [220]:
arr = np.array([1.75] * 20)
arr

array([1.75, 1.75, 1.75, 1.75, 1.75, 1.75, 1.75, 1.75, 1.75, 1.75, 1.75,
       1.75, 1.75, 1.75, 1.75, 1.75, 1.75, 1.75, 1.75, 1.75])

4. Создать вектор со значениями от 4 до 31

In [221]:
arr = np.array([i for i in range(4, 32)])
arr

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
       21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

5. Развернуть вектор (первый становится последним)

In [222]:
arr = np.array([i for i in range(4, 32)])
arr = arr[::-1]
arr

array([31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4])

6. Создать матрицу (двумерный массив) 3x3 со значениями от 1 до 9

In [223]:
mtr = np.arange(1,10).reshape(3, 3)
mtr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

7. Создать 3x3 единичную матрицу

In [224]:
mtr = np.eye(3)
mtr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

8. Создать 4x4 пустую матрицу

In [225]:
mtr = np.empty((3, 3))
mtr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

9. Создать единичную матрицу 4x4 со сдвигом на единицу вниз относительно главной диагонали

In [226]:
mtr = np.eye(3, 3, -2)
mtr

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 0., 0.]])

10. Создать тензор 3x3x3 со случайными значениями

In [227]:
import numpy.random as rnd
t = np.array(np.array([[[rnd.random()] * 3] * 3 for _ in range(3)]))
t

array([[[0.18385991, 0.18385991, 0.18385991],
        [0.18385991, 0.18385991, 0.18385991],
        [0.18385991, 0.18385991, 0.18385991]],

       [[0.39021838, 0.39021838, 0.39021838],
        [0.39021838, 0.39021838, 0.39021838],
        [0.39021838, 0.39021838, 0.39021838]],

       [[0.03656861, 0.03656861, 0.03656861],
        [0.03656861, 0.03656861, 0.03656861],
        [0.03656861, 0.03656861, 0.03656861]]])

11. Создать массив 5x5 со случайными значениями, найти минимум и максимум

In [228]:
arr = np.array([[rnd.random() for _ in range(5)] for _ in range(5)])
arr.max(), arr.min()

(np.float64(0.9770739845958339), np.float64(0.01897076164663114))

12. Создать случайный вектор размера 50 и найти среднее значение всех элементов

In [229]:
arr = np.array([rnd.random() for _ in range(50)])
avg = sum(arr) / len(arr)
avg

np.float64(0.4839187988826115)

13. Создать матрицу с 0 внутри, и 1 на границах

In [230]:
m, n = 5, 5
mat = np.matrix([[int(i == 0 or i == n - 1 or j == 0 or j == m - 1) \
                for i in range(n)] \
                for j in range(m)])
mat

matrix([[1, 1, 1, 1, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 1, 1, 1, 1]])

14. Создать 5x5 матрицу с 1,2,3,4 под диагональю

In [231]:
m, n = 5, 5
mat = np.matrix([[ i + 1 if i == j - 1 else 0 \
                for i in range(n)] \
                for j in range(m)])
mat

matrix([[0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [0, 2, 0, 0, 0],
        [0, 0, 3, 0, 0],
        [0, 0, 0, 4, 0]])

15. Перемножить матрицы 5x3 и 3x2

In [232]:
m, n, k = 5, 3, 2
mat1 = np.matrix([[ j * m + i \
                for i in range(n)] \
                for j in range(m)])

mat2 = np.matrix([[ j * k + i \
                for i in range(k)] \
                for j in range(n)])

np.dot(mat1, mat2)

matrix([[ 10,  13],
        [ 40,  58],
        [ 70, 103],
        [100, 148],
        [130, 193]])

16. Создать вектор состоящий из 15 элементов, поменять знак у элементов, значения которых между 6 и 12 

In [233]:
arr = np.array([i if i < 6 or i > 12 else -i for i in range(15)])
arr

array([  0,   1,   2,   3,   4,   5,  -6,  -7,  -8,  -9, -10, -11, -12,
        13,  14])

17. Создать 2 матрицы A(3x3) и B(3x3), получить матрицу С путем поэлеметного умножения.

In [234]:
A = np.array([[j * 3 + i for i in range(3)] for j in range(3)])
B = np.array([[j * 3 + i for i in range(3)] for j in range(3)])
C = A * B
C

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

18. Найти максимальные и минимальные значения матрицы С по строкам и столбцам

19. Создать вектор со значениями от 0 до 1 c 10 наблюдениями

In [235]:
arr = np.arange(0, 1, 0.1)
arr

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

20. Отсортировать вектор

In [236]:
arr = np.array(np.random.randint(1, 10, size=10))
print(arr)
print(np.sort(arr))

[3 9 2 8 8 1 2 1 7 6]
[1 1 2 2 3 6 7 8 8 9]


21. Проверить, одинаковы ли 2 numpy массива

In [237]:
arr1 = np.array(np.random.randint(1, 10, size=10))
arr2 = np.array(np.random.randint(1, 10, size=10))

print(arr1)
print(arr2)
print(all(arr1 == arr2))

[5 4 8 7 5 2 7 9 4 1]
[1 8 9 6 7 2 6 9 7 7]
False


22. Сделать массив неизменяемым

In [238]:
arr = np.array(np.random.randint(1, 10, size=10))

arr.flags.writeable = False

try:
    arr[0] = 0
except ValueError as e:
    print(e)

assignment destination is read-only


23. Создать случайный вектор из 20 элементов, найти квантиль от 10% и от 80%

In [270]:
arr = np.random.random(20)
print(arr)
print(np.quantile(arr, 0.1), np.quantile(arr, 0.8))

[0.9750896  0.96006514 0.75312113 0.25574769 0.38570854 0.20769218
 0.80344038 0.20100476 0.38607142 0.77030234 0.9786999  0.22719852
 0.0548357  0.12678512 0.31941426 0.39500603 0.7262615  0.28789034
 0.91882143 0.41464564]
0.1935827998923299 0.8265165918173111


24. Создать массив любой размерности состоящий из int и string

In [240]:
arr = np.array([1, "asd"], dtype=object)
arr

array([1, 'asd'], dtype=object)

25. Найти минимальное и максимальное значение, принимаемое каждым числовым типом numpy

In [241]:
# Write your code

26. Преобразовать массив из float в int

In [242]:
# Write your code

27. Отнять среднее из каждой строки в матрице

In [243]:
# Write your code

28. 

Дана данные из файла.

1,2,3,4,5

6,,,7,8

,,9,10,11

Необходимо прочитать его


In [244]:
# Write your code

29. Посчитайте сумму квадратов натуральных чисел от 1 до 10000.

In [245]:
# Write your code

## BLOKE №2 (tensors) 

1. Импортируйте pytorch

In [271]:
import torch

2. Создать вектор состящий из 10 элементов

In [273]:
torch.tensor(torch.arange(10))

/tmp/ipykernel_1248/2940118372.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  torch.tensor(torch.arange(10))


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

3. Создать тензор из python list

In [274]:
torch.tensor([1, 2, 3, 4])

tensor([1, 2, 3, 4])

4. Создать тензор из np.array

In [ ]:
arr = np.arange(27).reshape(3, 3, 3)
t = torch.tensor(arr)
t

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]])

5. Создать тензор с нормальным распределением

In [281]:
t = torch.normal(10, 5, (3, 3))
t

tensor([[18.9544,  8.3751,  3.3741],
        [ 0.3274,  8.4396, 10.8572],
        [10.4345, 10.1992,  7.6249]])

6. Создать тензор размером 3х3х3

In [282]:
t = torch.arange(27).reshape(3, 3, 3)
t

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]])

7. Создать единичную матрицу размером 4х5

In [283]:
t = torch.eye(4, 5)
t

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.]])

8. Создать вектор размера 25, заполнить елементами со значениме pi

In [ ]:
vec = torch.full([25], torch.pi)
vec

tensor([3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416,
        3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416,
        3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416])

9. Умножить матрицу размера 9, заполненная от 0 до 8, поэлементно на любое число

In [287]:
mtr = torch.arange(9).reshape(3, 3)
mtr = mtr * 3
mtr

tensor([[ 0,  3,  6],
        [ 9, 12, 15],
        [18, 21, 24]])

10. Создать произвольный тензор с типом данных int8

In [289]:
t = torch.full([3, 5, 2, 2], 1 ,dtype=torch.int8)
t

tensor([[[[1, 1],
          [1, 1]],

         [[1, 1],
          [1, 1]],

         [[1, 1],
          [1, 1]],

         [[1, 1],
          [1, 1]],

         [[1, 1],
          [1, 1]]],


        [[[1, 1],
          [1, 1]],

         [[1, 1],
          [1, 1]],

         [[1, 1],
          [1, 1]],

         [[1, 1],
          [1, 1]],

         [[1, 1],
          [1, 1]]],


        [[[1, 1],
          [1, 1]],

         [[1, 1],
          [1, 1]],

         [[1, 1],
          [1, 1]],

         [[1, 1],
          [1, 1]],

         [[1, 1],
          [1, 1]]]], dtype=torch.int8)

11. Изменить тип данных из пункта 10 на int64

In [290]:
t = torch.full([3, 5, 2, 2], 1 ,dtype=torch.int64)
t

tensor([[[[1, 1],
          [1, 1]],

         [[1, 1],
          [1, 1]],

         [[1, 1],
          [1, 1]],

         [[1, 1],
          [1, 1]],

         [[1, 1],
          [1, 1]]],


        [[[1, 1],
          [1, 1]],

         [[1, 1],
          [1, 1]],

         [[1, 1],
          [1, 1]],

         [[1, 1],
          [1, 1]],

         [[1, 1],
          [1, 1]]],


        [[[1, 1],
          [1, 1]],

         [[1, 1],
          [1, 1]],

         [[1, 1],
          [1, 1]],

         [[1, 1],
          [1, 1]],

         [[1, 1],
          [1, 1]]]])

12. Создать случайный тензор размера 4x5 и найти среднее по 2му столбцу.

In [303]:
t = torch.rand(4, 5)
avg = sum(t[1]) / len(t[1])
print(t)
avg

tensor([[0.9271, 0.9793, 0.9614, 0.3100, 0.7096],
        [0.1955, 0.3661, 0.2486, 0.0450, 0.9593],
        [0.4579, 0.9562, 0.2895, 0.4220, 0.1560],
        [0.5716, 0.0625, 0.6342, 0.0725, 0.8853]])


tensor(0.3629)

13. Создать пустой тензор произвольных размеров

In [304]:
t = torch.empty([3,3,3,3])
t

tensor([[[[6.2780e-01, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00]],

         [[0.0000e+00, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00]],

         [[0.0000e+00, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00]]],


        [[[0.0000e+00, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00]],

         [[0.0000e+00, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00]],

         [[0.0000e+00, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00]]],


        [[[0.0000e+00, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0

14. Скалярно умножить 2 вектора

In [305]:
v1 = torch.tensor([1, 2, 3])
v2 = torch.tensor([4, 5, 6])
torch.dot(v1, v2)

tensor(32)

15. Умножить матрицу на вектор

In [ ]:
v = torch.tensor([1, 2, 3])
mtr = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

r = torch.matmul(mtr, v)
r

tensor([14, 32, 50])

16. Перемножить 2D матрицы 

In [319]:
mtr1 = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
mtr2 = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

r = torch.matmul(mtr1, mtr2)
r

tensor([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

17. Перемножить 3D тензоры

In [324]:
t1 = torch.arange(27).reshape(3, 3, 3)
t2 = torch.arange(27).reshape(3, 3, 3)

torch.matmul(t1, t2)


tensor([[[  15,   18,   21],
         [  42,   54,   66],
         [  69,   90,  111]],

        [[ 366,  396,  426],
         [ 474,  513,  552],
         [ 582,  630,  678]],

        [[1203, 1260, 1317],
         [1392, 1458, 1524],
         [1581, 1656, 1731]]])

18. Создать вектор с нормальным распределением и вывести элементы больше 0.5

In [337]:
vec = torch.normal(1, 0.5, [10])

f = list(filter(lambda x: x > 0.5, vec))
print(f)

[tensor(1.0766), tensor(0.8967), tensor(0.5381), tensor(1.6810), tensor(1.4045), tensor(1.9286), tensor(1.0197), tensor(0.9838), tensor(0.5232), tensor(0.6893)]


19. Создать матрицу 3х3 заполненную единицами и заменить 1й столбец на 4

In [342]:
m = torch.full([3, 3], 1)
print(m)
m[:, 0] = torch.full([3], 4)
print(m)


tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])
tensor([[4, 1, 1],
        [4, 1, 1],
        [4, 1, 1]])


20. Создать матрицу и вывести сумму по каждой строке

In [347]:
m = torch.full([3, 3], 1)
print(m)

for i in m:
    print(sum(i))

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])
tensor(3)
tensor(3)
tensor(3)


20. Создать матрицу и вывести среднее по каждому столбцу

In [354]:
m = torch.rand([3, 3])
print(m)

for i in m.T:
    print(sum(i)/len(i))

tensor([[0.8119, 0.1522, 0.7526],
        [0.4938, 0.6710, 0.0628],
        [0.3854, 0.0709, 0.0794]])
tensor(0.5637)
tensor(0.2980)
tensor(0.2983)


21. Создать 2 вектора и сконкатенировать по 1 оси

In [357]:
v1 = torch.tensor([1, 2, 3])
v2 = torch.tensor([4, 5, 6])

torch.cat((v1, v2), dim=0)

tensor([1, 2, 3, 4, 5, 6])

22. Перемножим две большие единичные матрицы. 
Сначал на центральном процессоре, затем попробуйте на GPU

In [360]:
m1 = torch.tensor([[1, 2],
                   [3, 4]])
m2 = torch.tensor([[5, 6],
                   [7, 8]])

cpu = torch.matmul(m1, m2)
print(cpu)

if torch.cuda.is_available():
    m1_gpu = m1.to('cuda')
    m2_gpu = m2.to('cuda')

    gpu = torch.matmul(m1_gpu, m2_gpu) 

    result = gpu.to('cpu')
    print(result)
else:
    print("GPU недоступен.")

tensor([[19, 22],
        [43, 50]])
GPU недоступен.
